version: '3.8'

services:

  app:
    build:
      context: .
      dockerfile: Dockerfile  # Use your custom Dockerfile (with pdo_mysql)
    container_name: laravel_app
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    networks:
      - laravel
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: laravel_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ByteQuest
      MYSQL_USER: aman
      MYSQL_PASSWORD: aman@pass1
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel
  
  nginx:
    image: nginx:latest
    container_name: laravel_nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
      - mysql
    networks:
      - laravel

networks:
  laravel:

volumes:
  mysql_data:
